### ISSUE TITLE
Crafting stuff..

### ISSUE THREAD

**Issue by GronbergInfo** [cameroncondry/cbc-kitten-scientists#159] opened 2016-02-04 18:49 UTC
Hi, i have just recently noticed, after my umphteen reset (3-4 times with KS).
When my catnip is maxed.. and wood is not way near max (like 2k / 12k), Ks doesnt trade nip's for wood. Trigger is at 0.95. and not set to limited.

**Comment by oliversalzburg** [comment] 2016-02-06 13:24
Could be that you're still missing Catpower or Gold for a trade to be triggered.

**Comment by GronbergInfo** [comment] 2016-02-06 13:24
trading catnip for wood does NOT require catpower nor gold.

**Comment by oliversalzburg** [comment] 2016-02-06 13:30
Ah, you're right. It's not a trade at all, it's a craft :P No idea why that would happen, it's working fine in my games :\

If you're still having the issue, could you share your game state (Options → Export)?

**Comment by GronbergInfo** [comment] 2016-02-07 16:36
I atm have problem that the script wont build many buildings. I am talking about VERY LATE GAME!
I have set the building trigger to 0.001, and yet my storages is more or less maxed at most stuff.
Game export: http://pastebin.com/CCAy8Tma
I only more or less see steel crafting in my log


`
Kittens have crafted 585.062K Steel

Kittens have crafted 564.979K Steel

Kittens have crafted 514.771K Steel

Kittens have crafted 389.261K Steel
Year 323 - SpringA rift to the Unicorn Dimension has opened in your village, +500 unicorns!Kittens have crafted 374.707K Steel
Year 323 - SpringIvory Meteor fell near the village, +7650 ivory!Kittens have crafted 338.323K Steel

Kittens have crafted 247.354K Steel

Kittens have crafted 319.162K Steel
Year 323 - SpringIvory Meteor fell near the village, +6885 ivory!Kittens have crafted 199.450K Steel

Kittens have crafted 199.450K Steel

Kittens have crafted 199.392K Steel

Kittens have crafted 199.238K Steel

Kittens have crafted 198.912K Steel

Kittens have crafted 198.029K Steel

Kittens have crafted 195.859K Steel

Kittens have crafted 190.426K Steel

Kittens have crafted 176.870K Steel

Kittens have crafted 142.963K Steel

Kittens have crafted 58.176K Steel

Kittens have built a new ObservatoryKittens have crafted 727.680K Steel
Year 323 - SpringIvory Meteor fell near the village, +4190 ivory!Year 323 - SpringYour hunters have returned from 2878 hunts. +539.942K furs, +173.375K ivoryYear 323 - Spring159 unicorns!Sent 287.844K kittens on the huntKittens have crafted 622.368K Steel

Kittens have crafted 216.917M WoodKittens have crafted 598.406K Steel

Kittens have crafted 216.917M WoodKittens have crafted 568.454K Steel

Kittens have crafted 523.546K Steel

Kittens have crafted 411.206K Steel

Kittens have crafted 216.917M WoodKittens have built a new LibraryKittens have crafted 399.706K Steel

Kittens have crafted 216.917M WoodKittens have built a new LibraryKittens have built a new WorkshopKittens have crafted 339.926K Steel

Kittens have crafted 216.917M WoodKittens have built a new MineKittens have crafted 216.917M WoodKittens have built a new ObservatoryKittens have built a new WorkshopKittens have built a new MineYear 323 - SpringSave import successful!Year 323 - SpringBlack rain is falling over the villageKittens have crafted 393.850K Steel

Kittens have crafted 386.189K Steel

Kittens have crafted 367.027K Steel

Kittens have crafted 319.142K Steel

Kittens have crafted 199.392K Steel

Kittens have crafted 199.296K Steel

Kittens have crafted 198.989K Steel

Kittens have crafted 198.259K Steel

Kittens have crafted 196.435K Steel

Kittens have crafted 191.885K Steel

Kittens have crafted 180.499K Steel

Kittens have crafted 152.026K Steel

Kittens have crafted 80.813K Steel

Kittens have built a new ObservatoryKittens have crafted 784.301K Steel

Kittens have crafted 763.872K Steel

Kittens have crafted 712.800K Steel
Year 323 - SpringYour hunters have returned from 2831 hunts. +529.438K furs, +171.071K ivoryYear 323 - Spring146 unicorns!Sent 283.189K kittens on the huntKittens have crafted 585.178K Steel
Year 323 - SpringAn Alicorn has descended from the sky!Kittens have crafted 565.286K Steel

Kittens have crafted 515.616K Steel
Year 323 - SpringA rift to the Unicorn Dimension has opened in your village, +500 unicorns!Kittens have crafted 391.411K Steel

Kittens have crafted 380.102K Steel

Kittens have crafted 351.821K Steel
Year 323 - SpringAn Alicorn has descended from the sky!Kittens have crafted 281.146K Steel

Kittens have crafted 216.917M WoodKittens have built a new LibraryKittens have crafted 216.917M WoodKittens have built a new ObservatoryKittens have built a new WorkshopYear 323 - SpringSave import successful!
reddit | wiki | help | credits | donate
`

**Comment by GronbergInfo** [comment] 2016-02-09 20:18
With this save game, the script does not build anything.. and rarely crafts steel
http://pastebin.com/nWLYpfNk

Summary of the last 25 years and 399.8 days
Craft: +8.244G Wood
Craft: +364.147M Megalith
Craft: +1.159G Plate
Craft: +1.101M Blueprint
Craft: +18.158M Kerosene
Craft: +1.318M Compendium
Craft: +3.070M Manuscript
Craft: +98.380M Parchment
Craft: +6.922G Steel
Sent 2.401M adorable kitten hunters
Accumulated 14.842M by praising the sun
Held 26 festivals

**Comment by GronbergInfo** [comment] 2016-02-09 20:22
I have tried to set building trigger to 0.00001 and still nothing.

**Comment by oliversalzburg** [comment] 2016-02-09 20:26
What happens when you reload the page and enable KS again? Does it start building?

**Comment by oliversalzburg** [comment] 2016-02-09 20:30
I'm looking at Log Houses and they are instantly being built as soon as I enable KS. In general though, a trigger of `0` is just fine if you want to build instantly. I'm not sure if the value you've given could be an issue, but your value is working fine for me as well.

**Comment by GronbergInfo** [comment] 2016-02-09 20:34
Tried that:
`
Year 542 - SummerYour hunters have returned from 2928 hunts. +545.651K furs, +176.148K ivory
Year 542 - Summer
160 unicorns!Sent 292.859K kittens on the hunt
Kittens have crafted 3.361M Steel
Kittens have crafted 3.361M Steel
Kittens have crafted 3.361M Steel
Year 542 - SummerYour hunters have returned from 2928 hunts. +532.413K furs, +179.766K ivory
Year 542 - Summer147 unicorns!
Sent 292.858K kittens on the hunt
Kittens have crafted 3.361M Steel
Kittens have crafted 3.361M Steel
Kittens have crafted 52.793K Kerosene
Year 542 - Summer
A rift to the Unicorn Dimension has opened in your village, +500 unicorns!
Year 542 - Summer
Your hunters have returned from 2921 hunts. +541.421K furs, +168.573K ivoryYear 
542 - Summer
153 unicorns!Sent 292.148K kittens on the hunt
Kittens have crafted 3.361M Steel
Kittens have crafted 3.361M Steel
Kittens have crafted 7.834M Plate
Kittens have crafted 10.659K Blueprint
Year 542 - SummerYour hunters have returned from 3052 hunts. +573.495K furs, +181.705K ivory
Year 542 - Summer146 unicorns!
Sent 305.285K kittens on the hunt
Kittens have crafted 12.728K Compendium
Kittens have crafted 29.636K Manuscript
Kittens have crafted 966.270K Parchment
Kittens have crafted 3.361M Steel
Kittens begin holding a festivalYear 542 - Summer
The cultural festival has startedEnabled
- here i enabled KS again -`
Also. i notice that kitten-buildings always gets de-selected no matter what i have enabled before.

**Comment by oliversalzburg** [comment] 2016-02-09 20:35
What browser and operating system are you on?

**Comment by GronbergInfo** [comment] 2016-02-09 20:37
Xubuntu 15.10
Firefox what ever that is latest.. says 44.0.

**Comment by GronbergInfo** [comment] 2016-02-09 20:39
To add, i play at http://bloodrizer.ru/games/kittens/# and not Kong. if "that matters".

**Comment by oliversalzburg** [comment] 2016-02-09 20:43
Please open the **Storage Inspector** (<kbd>Shift</kbd>+<kbd>F9</kbd>), navigate to **Local Storage** → **http://bloodrizer.ru** and locate the `cbc-kitten-scientists` key.

Select that key and mark the `cbc.kitten-scientists` entry on the right-hand side under **Data**. Copy the value to the clipboard and put it on https://gist.github.com/ or http://pastie.org/

**Comment by GronbergInfo** [comment] 2016-02-09 20:45
Unfortanetly, Shift+F9 does not produce any thing (on linux/failfox)

**Comment by oliversalzburg** [comment] 2016-02-09 20:46
Then please try clicking the hamburger menu and navigate to **Developer** → **Storage Inspector**. I don't have Ubuntu running right now, sorry :\

**Comment by GronbergInfo** [comment] 2016-02-09 20:55
When i did that, this is how FF looks like: http://i.imgur.com/9grCy06.png

**Comment by oliversalzburg** [comment] 2016-02-09 20:59
This is what we're looking for:
![](https://i.imgur.com/cbooKoF.png)

**Comment by GronbergInfo** [comment] 2016-02-09 21:00
That is where my picture are from, when i clicked it, i got taken there.

**Comment by oliversalzburg** [comment] 2016-02-09 21:04
Click the cogwheel icon on the far right, then enable the **Storage** module.

![](https://i.imgur.com/HBXq7vU.png)

**Comment by oliversalzburg** [comment] 2016-02-09 21:08
Alternatively, you should be able to simply enter `localStorage` into the developer console and grab the value from the output.

**Comment by GronbergInfo** [comment] 2016-02-09 21:08
http://i.imgur.com/jZenRuj.png

**Comment by oliversalzburg** [comment] 2016-02-09 21:09
Yeah, it's the first entry in that list.

**Comment by GronbergInfo** [comment] 2016-02-09 21:10
I cannot find a way to tope the full info.. r-click doesnt give a meny. ctrl-c doesnt give a copy :(

**Comment by GronbergInfo** [comment] 2016-02-09 21:11
I use this to load the script: 

`javascript:(function(){var d=document,s=d.createElement('script');s.src='https://rawgit.com/cameroncondry/cbc-kitten-scientists/master/kitten-scientists.user.js';d.body.appendChild(s);})();
`

**Comment by oliversalzburg** [comment] 2016-02-09 21:12
When you mark the entry, you should get a new panel on the right-hand side. In there, you should be able to copy the value with <kbd>Ctrl</kbd>+<kbd>C</kbd>.

**Comment by oliversalzburg** [comment] 2016-02-09 21:13
If that doesn't work either. Please try typing `localStorage` into the Console and try grabbing the value from the output.

**Comment by GronbergInfo** [comment] 2016-02-09 21:13
`cbc.kitten-scientists:"{"version":1,"items":{"toggle-hut":false,"toggle-logHouse":false,"toggle-mansion":false,"toggle-workshop":true,"toggle-factory":true,"toggle-field":false,"toggle-pasture":false,"toggle-solarFarm":false,"toggle-mine":true,"toggle-lumberMill":true,"toggle-aqueduct":false,"toggle-hydroPlant":true,"toggle-oilWell":true,"toggle-quarry":true,"toggle-smelter":false,"toggle-biolab":false,"toggle-calciner":false,"toggle-reactor":false,"toggle-accelerator":false,"toggle-steamworks":false,"toggle-magneto":true,"toggle-library":true,"toggle-academy":true,"toggle-observatory":true,"toggle-amphitheatre":true,"toggle-broadcastTower":true,"toggle-tradepost":true,"toggle-chapel":true,"toggle-temple":true,"toggle-mint":false,"toggle-unicornPasture":true,"toggle-ziggurat":true,"toggle-chronosphere":true,"toggle-barn":true,"toggle-harbor":true,"toggle-warehouse":true,"toggle-wood":true,"toggle-limited-wood":false,"toggle-beam":false,"toggle-limited-beam":false,"toggle-slab":false,"toggle-limited-slab":false,"toggle-steel":true,"toggle-limited-steel":false,"toggle-plate":true,"toggle-limited-plate":false,"toggle-alloy":false,"toggle-limited-alloy":false,"toggle-concrete":false,"toggle-limited-concrete":true,"toggle-gear":false,"toggle-limited-gear":true,"toggle-scaffold":false,"toggle-limited-scaffold":true,"toggle-ship":true,"toggle-limited-ship":true,"toggle-tanker":false,"toggle-limited-tanker":true,"toggle-parchment":true,"toggle-limited-parchment":true,"toggle-manuscript":true,"toggle-limited-manuscript":true,"toggle-compendium":true,"toggle-limited-compendium":true,"toggle-blueprint":true,"toggle-limited-blueprint":true,"toggle-kerosene":true,"toggle-limited-kerosene":false,"toggle-megalith":true,"toggle-limited-megalith":true,"toggle-eludium":true,"toggle-limited-eludium":true,"toggle-dragons":true,"toggle-dragons-spring":true,"toggle-dragons-summer":true,"toggle-dragons-autumn":true,"toggle-dragons-winter":true,"toggle-zebras":true,"toggle-zebras-spring":true,"toggle-zebras-summer":true,"toggle-zebras-autumn":true,"toggle-zebras-winter":true,"toggle-lizards":false,"toggle-lizards-spring":false,"toggle-lizards-summer":true,"toggle-lizards-autumn":false,"toggle-lizards-winter":false,"toggle-sharks":false,"toggle-sharks-spring":false,"toggle-sharks-summer":false,"toggle-sharks-autumn":false,"toggle-sharks-winter":true,"toggle-griffins":false,"toggle-griffins-spring":false,"toggle-griffins-summer":false,"toggle-griffins-autumn":true,"toggle-griffins-winter":false,"toggle-nagas":true,"toggle-nagas-spring":true,"toggle-nagas-summer":false,"toggle-nagas-autumn":false,"toggle-nagas-winter":false,"toggle-spiders":false,"toggle-spiders-spring":false,"toggle-spiders-summer":false,"toggle-spiders-autumn":true,"toggle-spiders-winter":false,"toggle-leviathans":true,"toggle-leviathans-spring":true,"toggle-leviathans-summer":true,"toggle-leviathans-autumn":true,"toggle-leviathans-winter":true,"toggle-spaceElevator":true,"toggle-sattelite":false,"toggle-spaceStation":false,"toggle-moonOutpost":false,"toggle-moonBase":false,"toggle-planetCracker":false,"toggle-hydrofracturer":false,"toggle-researchVessel":false,"toggle-orbitalArray":false,"toggle-sunlifter":false,"toggle-cryostation":false,"toggle-spaceBeacon":false},"resources":{"furs":{"stock":1000},"unobtainium":{"consume":1},"minerals":{"stock":1000000,"consume":0.6},"wood":{"stock":0,"consume":0.6},"coal":{"stock":0,"consume":0.6},"iron":{"stock":0,"consume":0.6},"catnip":{"stock":350000,"consume":0.6},"beam":{"stock":0,"consume":0.6},"slab":{"stock":0,"consume":0.6},"concrate":{"stock":0,"consume":0.6},"plate":{"stock":0,"consume":0.6},"steel":{"stock":0,"consume":0.6},"alloy":{"stock":0,"consume":0.6},"gear":{"stock":0,"consume":0.6},"scaffold":{"stock":0,"consume":0.6},"ship":{"stock":0,"consume":0.6},"parchment":{"stock":0,"consume":0.6},"manuscript":{"stock":0,"consume":0.6},"compedium":{"stock":0,"consume":0.6},"starchart":{"stock":3000,"consume":0.6}},"triggers":{"faith":0.99,"hunt":0.8,"build":0,"space":0.95,"craft":0.95,"trade":1}}"`

**Comment by GronbergInfo** [comment] 2016-02-09 21:16
I changed building trigger to 0 a while ago.. and yet.. no new buildings are built.

**Comment by oliversalzburg** [comment] 2016-02-09 21:16
Alright! We're there :) What buildings would you expect to be built with this config?

**Comment by GronbergInfo** [comment] 2016-02-09 21:18
Anything from this, i would expect to be built with 0 trigger: http://i.imgur.com/c1P6hbV.png

**Comment by oliversalzburg** [comment] 2016-02-09 21:19
When you click **items** in the **Building** section, you'll see that every that *can* be built is not checked, unless I'm mistaken.

**Comment by GronbergInfo** [comment] 2016-02-09 21:20
All is checked: http://imgur.com/DTQh6Rg

**Comment by oliversalzburg** [comment] 2016-02-09 21:22
Huh, that's not what the settings reflect though:
![image](https://cloud.githubusercontent.com/assets/1658949/12930959/9252665a-cf7b-11e5-830b-1d621adb012a.png)

Not sure what is happening here. Do you see any errors in the Console when you toggle items?

**Comment by GronbergInfo** [comment] 2016-02-09 21:25
I am not sure how "settings" and "real life"should differ, since i do not change anything in the KS script to my knowledge.

And i cannot see anything in the console that would be printed out in some error either.

**Comment by oliversalzburg** [comment] 2016-02-09 21:28
Well, it appears as if, for some reason, your changes in the user interface have no effect on KS at all. Your changes are not persisted into the script and they are not persisted into the local storage.

You could try if running the script through Greasemonkey changes anything. But I'm a bit clueless right now how this situation could have happened.

**Comment by GronbergInfo** [comment] 2016-02-09 21:30
I have tried the GS way. but it never loaded/started for me at all.
thats why i am loading the script manually thru F12 stuff in FF.

**Comment by oliversalzburg** [comment] 2016-02-09 21:36
You're loading it through the developer console? Does it make a difference if you're using a bookmarklet?

**Comment by GronbergInfo** [comment] 2016-02-10 15:20
Made a bookmarklet, and now building seems to work, also updated firefox the other day

**Comment by GronbergInfo** [comment] 2016-02-10 15:21
Nope, it only built once or twice, now its only hunting and crafting the same stuff over and over, i have almost 2G steel forexample.. but no Alloy.

**Comment by GronbergInfo** [comment] 2016-02-10 18:55
fter i reset and left the game and KS run for a few hours..

This is what i see with what i believe everything enabled:

`Year 7 - SpringYour hunters have returned. +123 furs, +79 ivorySent 118.800 kittens on the huntYear 7 - SpringYour hunters have returned. +60 furs, +74 ivorySent 114.214 kittens on the huntKittens have crafted 4.18 ParchmentYear 7 - SpringYour hunters have returned. +139 fursSent 109.628 kittens on the huntKittens have crafted 4.18 ParchmentKittens have crafted 1258.00 WoodYear 7 - SpringYour hunters have returned. +135 fursSent 105.042 kittens on the huntYear 7 - SpringYour hunters have returned. +49 fursSent 100.456 kittens on the huntYear 7 - SpringYour hunters have returned. +67 fursSent 148.163 kittens on the huntKittens have crafted 4.18 ParchmentYear 7 - SpringYour hunters have returned. +83 furs, +52 ivorySent 143.576 kittens on the huntYear 7 - SpringYour hunters have returned. +90 furs, +85 ivorySent 138.990 kittens on the huntPraised the sun!Year 7 - SpringYour hunters have returned. +99 furs, +72 ivorySent 134.404 kittens on the huntKittens have crafted 4.18 ParchmentKittens have crafted 4.18 SteelYear 7 - SpringYour hunters have returned. +115 fursSent 129.818 kittens on the huntKittens have crafted 1245.00 WoodKittens have crafted 4.18 ParchmentYear 7 - SpringYour hunters have returned. +92 furs, +50 ivoryYear 7 - Spring1 unicorns!Sent 125.232 kittens on the huntYear 7 - SpringYour hunters have returned. +36 fursSent 120.646 kittens on the huntYear 7 - SpringYour hunters have returned. +105 furs, +39 ivorySent 116.060 kittens on the huntKittens have crafted 4.18 ParchmentYear 7 - SpringYour hunters have returned. +164 fursSent 111.473 kittens on the huntYear 7 - SpringYour hunters have returned. +52 furs, +32 ivorySent 106.887 kittens on the huntKittens have crafted 4.18 ParchmentYear 7 - SpringYour hunters have returned. +77 furs, +80 ivorySent 102.301 kittens on the huntKittens have crafted 4.18 ParchmentKittens have crafted 1208.00 WoodYear 7 - SpringYour hunters have returned. +135 furs, +30 ivoryYear 7 - Spring1 unicorns!Sent 150.008 kittens on the huntYear 7 - SpringYour hunters have returned. +53 furs, +62 ivorySent 145.422 kittens on the huntKittens have built a new WorkshopYear 7 - SpringYour hunters have returned. +63 fursSent 135.606 kittens on the huntKittens have crafted 4.12 ParchmentYear 7 - SpringYour hunters have returned. +105 furs, +13 ivorySent 131.020 kittens on the huntYear 7 - SpringYour hunters have returned. +99 fursSent 126.434 kittens on the huntKittens have crafted 4.12 ParchmentYear 7 - SpringYour hunters have returned. +152 fursSent 121.848 kittens on the huntKittens have crafted 1258.00 WoodKittens have crafted 4.12 ParchmentYear 7 - SpringYour hunters have returned. +117 fursSent 117.262 kittens on the hunt`

**Comment by oliversalzburg** [comment] 2016-02-10 19:51
Yeah, I have no idea what's going on there. It could be an issue specific to your platform, even though I find that hard to believe.

Finding the cause of this would require some serious debugging, but the issue can't be reproduced on my machine. 

You could try if the problem persists in a new profile and/or another browser (like Chromium).

**Comment by oliversalzburg** [comment] 2016-02-11 20:41
@GronbergInfo Does it seem plausible to you that what you're experiencing is related to the **enable all** action not actually enabling anything internally?

**Comment by GronbergInfo** [comment] 2016-02-12 18:57
@oliversalzburg: No idea, but every reload of page and enabling KS, kitten stuff is disabled.

**Comment by GronbergInfo** [comment] 2016-02-12 19:00
Another Wierdness.. ATM, after a reset 1-2 days ago.. KS only seems determined to craft steel.. and only one time per time... 99.999% of messages is of one time steel crafting.

KS seems to "lock up" on something and ONLY do that.

Disabling the kitten scientists!
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel
Kittens have crafted 317.00 Steel
Kittens have crafted 7401.95 Manuscript
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel
Year 223 - AutumnYour hunters have returned from 988 hunts. +175.855K furs, +59.434K ivoryYear 223 - 

Autumn43 unicorns!
Sent 98.802K kittens on the hunt
Kittens have crafted 332.85 Steel
Kittens have built a new Mine
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel
Kittens have crafted 5769.40 Compendium
Kittens have crafted 301.15 Steel
Year 223 - Autumn
Ivory Meteor fell near the village, +1486 ivory!
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel
Kittens have crafted 301.15 Steel

**Comment by Wymrite** [comment] 2019-08-13 01:25
Fixed as of #248, was a result of the enable-all glitch.

**Closed by Wymrite** 2019-08-13 01:25 UTC
Labels: type:bug
