### ISSUE TITLE
Relocated Options no longer function

### ISSUE THREAD

**Issue by Caittus** [cameroncondry/cbc-kitten-scientists#264] opened 2019-10-15 23:12 UTC
Since reloading the Oct-14-19 build, none of the functions moved to the new Options sections are working, I've tried toggling Hold Festivals, Auto Praise, Hunt, and Trade Blackcoin repeatedly, but none of them function. All other functions outside of the new category continue to work correctly.

**Comment by Wymrite** [comment] 2019-10-15 23:30
Is your overall options menu enabled?

**Comment by Caittus** [comment] 2019-10-15 23:31
Yes. It's still trying to fire off the Explore code if I enable that, but it's not sending off any of the other functions.

**Comment by Caittus** [comment] 2019-10-15 23:42
Fiddling with it more, if I disable Force Ships to 243, Auto Praise and Hunt both start working, though it's still not doing Festivals or Blackcoins.

**Comment by Wymrite** [comment] 2019-10-16 00:06
Found a stray return statement that could prevent auto praise from occurring and pushed a hotfix just now. Auto praise, hunting, and holding festivals all appear to work as intended with the hotfix. Festivals have been changed in the latest update to only fire when they are not a negative drain on the economy. Haven't retested blackcoin trading yet, what's the current price and what is the trigger set to? Please let me know if the hotfix fixes the menu for you.

**Comment by Caittus** [comment] 2019-10-16 00:35
Seems to be working fine now; I cloned my save and hit it with an editor to set the blackcoin price high and low and it seems to be functioning correctly now on all counts.

**Comment by Wymrite** [comment] 2019-10-16 00:39
Good to hear, thanks for bringing this to our attention. I'll close the issue for now then.

**Closed by Wymrite** 2019-10-16 00:39 UTC
