### ISSUE TITLE
One more possible tweak to crafting items with no-limit-capped components

### ISSUE THREAD

**Issue by DirCattus** [cameroncondry/cbc-kitten-scientists#58] opened 2015-05-18 20:41 UTC
I love that we can now limit crafting items whose components don't have an upper limit cap. However, there are a few items (especially gears and the writing items) whose components grow so slowly that, even limited, the new items quickly outgrow the components

I feel one more check could solve this issue: If the "Limited" box is checked, it does all of the checks it currently does, plus a check to make sure the current component amount is twice that of the current item amount. Using steel and gears as an example, if you have 12k gears, no more would be made until the steel amount is greater than 24k (double the amount of gears). And since the current code only uses 50% of the current stock, it would use 12k of the steel, making (doing the math without any upgrades) 800 gears. That means that the next time gears would be automatically crafted is when steel was at 25.6k.

**Comment by jacob-keller** [comment] 2015-05-18 21:29
The best solution to this is stocks, I think, but the problem here obviously is automating growth of stocks.

**Comment by jacob-keller** [comment] 2015-05-18 21:30
Actually, I think I like something along these lines more than the current per-season limit.

**Comment by jacob-keller** [comment] 2015-05-18 21:32
For things like gears it's not a big deal, because gears you can craft on your own time, since it doesn't require anything but steal. (no limited input).

Generally I think the best solution is something along the lines of stocks, because you can strictly set how much steel it will save, for example.

**Comment by andrealessi** [comment] 2015-05-20 02:44
After a little while to play around with stocks, I'm not sure they're the answer here.  The problem is that when you have two items that use the same component (e.g. gears and alloy), autocrafting will always prioritise the item with the simplest requirements, in this case gears, because they don't rely on titanium the way alloy does.  Even if you set a stock amount for steel, gears are greedily prioritised once you're past the stock amount unless titanium is also at or near cap, which it generally won't be until much later in the game. (And you initially need titanium to craft titanium-producing buildings so it's not self-correcting.)  Once titanium drops back down from crafting some alloy, gears start being crafted again.

Even limiting gear crafting per-season while not limiting alloy crafting results in a fairly significant imbalance between gears and alloy because of titanium starvation.

**Comment by jacob-keller** [comment] 2015-05-20 02:59
That's true, but finding a good solution is difficult.

I've played around with the per-season limiters, and found them mostly just frustrating.

I really like your idea above, but I think we need to see it implemented in practice.

The core issue we have is trying to determine the most efficient route to create various resources.

Personally,  for gears, and other "simple" goods that rely solely on uncapped goods, I've found that you  can just set a reasonably large stock for, say, steel, and then make gears when you need them instead of trying to automate them.

This doesn't solve the issue of multiple items requiring the same good. We get this with trades, as well as with crafts and buildings.

We have some difficult problems in regards to hunting vs trading that we resolved by simply having trading ignore catpower totals.

There is an internal "max" field that is currently not configurable, and this might work but again has limits due to not being dynamic.

The problem with the above system mentioned I have is for how to handle multiple resources.

should it apply to all resources? only uncapped resources? I'm not really sure here..

I'd like to find a good solution that we can apply to these problems.

**Comment by kaeroku** [comment] 2017-12-25 06:35
Would a "max stock" option be workable for auto-crafting? This would be distinct from the "trigger point" as it would be a limit switch, essentially, that says "don't craft any more of this item if we already have X crafted."

This way, you could create gears until, e.g., a stock of 1000 is reached and then it won't auto-craft any more gears, freeing up the steel for other projects. If you set this on multiple goods which require the same resources, KS would eventually craft all of them. You just leave the one (or two, if they have some different requirements) resources that you don't want limited without the cap, so any of the resources that go into it can continue being consumed to auto-craft while you're away.

This would require *some* degree of user management, just like stocks do, but would solve the issue indicated.

**Comment by jacob-keller** [comment] 2018-04-05 21:59
I think we can't really tell without trial implementations.

**Comment by Wymrite** [comment] 2019-08-13 01:19
Current implementation of limited prevents items becoming unbalanced with their components.

**Closed by Wymrite** 2019-08-13 01:19 UTC
