### ISSUE TITLE
Leviathans trades not happening

### ISSUE THREAD

**Issue by pefoley2** [cameroncondry/cbc-kitten-scientists#49] opened 2015-05-14 23:44 UTC
KittenScientists doesn't seem to actually trade with Leviathans even though I have enough unobtanium, and can trigger the trades manually.

**Comment by jacob-keller** [comment] 2015-05-14 23:57
You have them enables and in season?

**Comment by pefoley2** [comment] 2015-05-15 00:18
Yeah

**Comment by jacob-keller** [comment] 2015-05-15 00:30
Interesting. Is your unobtainium nearly full?

**Comment by pefoley2** [comment] 2015-05-15 00:37
I've come back to it being completely full, but even dropping the trigger ratio down to 0.5 didn't seem to help.

**Comment by jacob-keller** [comment] 2015-05-15 01:03
I will take a look

**Comment by jacob-keller** [comment] 2015-05-15 01:26
How much Unobtanium can you store?

It seems to be possibly an issue with the getLowestTradeAmount function, but I can't currently further test anything, because I don't have them unlocked, and can only store 3k unobtanium currently.

Do you have a debug console (Chrome = Ctrl + Shift + J)?

If you do, try running:

t = new TradeManager()
t.getLowestTradeAmount('leviathans')

And let me know what the result is (when you're capped).

**Comment by cameroncondry** [comment] 2015-05-15 01:38
A person on the reddit thread mentioned leviathans not working as intended either. I suspected it was due to the multitude of caps, but it needs to be researched a bit more for a fix. (if one is needed)

**Comment by pefoley2** [comment] 2015-05-15 01:46
Cap is 7974.300.
Trade amount is 0 when it's capped.

**Comment by pefoley2** [comment] 2015-05-15 01:48
Could it be because I already have max sorrow?

**Comment by jacob-keller** [comment] 2015-05-15 01:48
That's it.

**Comment by jacob-keller** [comment] 2015-05-15 02:00
It tries to avoid trading with races if it wouldn't "earn" anything.. but it's hard to say that when not all races give uncapped goods.

I suggest maybe we find a way to fix that. It will trade as long as at least one of the capped goods isn't fully capped, but I'm not sure if that's good.

The goal was to prevent trading when there was little benefit.

**Comment by jacob-keller** [comment] 2015-05-15 02:23
I think this is fixed now with #47 pull request, I chose to add an "allowuncapped" resource, and set it for leviathan. The other races don't seem to produce much outside of blueprints that is capped, but if you want you can change this field to allow it for any race in the debugger.

**Comment by Mewnine** [comment] 2015-05-16 23:00
Adding to this, is there a way to trade everything or simply always trade? I'd like to push out as much leviathan trades as I can while they are there and I'm afk.

**Comment by pefoley2** [comment] 2015-05-16 23:05
Yeah, I'd like to be able to force leviathan trades to happen as often as possible too.

**Comment by jacob-keller** [comment] 2015-05-16 23:11
That should work once the fix is in place.  Leviathan won't check if it can
store all its stuff

**Comment by pefoley2** [comment] 2015-05-16 23:12
I was thinking more trade as soon as it hits 5K unobntanium so that it happens before the elder gods depart.

**Comment by jacob-keller** [comment] 2015-05-16 23:14
I suggest lowering the trade trigger % via the console then.

**Comment by jacob-keller** [comment] 2015-05-17 08:08
For clarification:

you can edit

options.auto.trade.trigger = 0

 to set the trigger percent to 0 so it will always try to trade each round, and modify

options.auto.trade.items.leviathan.trigger = 0

to make it always try leviathan without checking trigger

Then, once my patch series lands, it will include the fix that modifies so that leviathans don't check if they can store the result, you can modify this per race by editing

options.auto.trade['race'].allowcapped = true

if you need this behavior for other races.

I think that with teh ability to modify these settings from the console, and the fix for leviathans checking sorrow cap in place this should be enough to address the concerns.

We can't make the interface 100% for every person's needs, though maybe leviathans specifically need something due to the way the elder gods depart. I am not sure yet.

**Comment by cameroncondry** [comment] 2015-05-17 20:28
I am still yet to get to heavy leviathan trading, however, I do see merit in giving it an unlimited option during the event. Either something that checks for the event automatically, or a toggle that simply makes the resource trade regardless of limits.

**Comment by jacob-keller** [comment] 2015-05-17 22:15
At least we avoid the limits for leviathan now.

**Comment by jacob-keller** [comment] 2015-05-21 05:13
This should be fully fixed for now at least in terms of allowing trades even when sorrow is capped. I had a typo and used allowuncapped instead of allowcapped.

**Comment by jacob-keller** [comment] 2015-05-22 23:59
This should be fixed in master if you could re-try it again and see if this fixes the issue you had?

**Comment by Mewnine** [comment] 2015-05-23 12:44
My leviathan trades have been going off perfectly. had the script on for a day and came back to a lot of time crystals. That was actually a few days ago already before the typo was even fixed.

**Comment by jacob-keller** [comment] 2015-05-23 14:37
Ya they work as long as sorrow wasn't capped and you had enough
unobtainium.

**Comment by oliversalzburg** [comment] 2015-12-30 17:15
It seems to me like this is no longer a problem. KS has been trading fine with Leviatihans for me for quite some time. The only thing that is a problem is when you're also crafting Eludium, because the limits of crafting and trading can conflict with each other.

Either way, I don't think there is a general issue with Leviathan trading.

**Closed** 2015-12-31 17:12 UTC
Labels: bug, enhancement
