### ISSUE TITLE
not building space

### ISSUE THREAD

**Issue by idgfight** [cameroncondry/cbc-kitten-scientists#160] opened 2016-02-11 18:09 UTC
My kitten scientists isn't building space for some reason.  I have everything enabled and my trigger value set really low but nothing seems to be working.  I'm using Chrome for mac if that makes any difference.  I'm also pretty late into the game and I have a massive faith bonus if that affects anything.  It used to work but hasn't been the last two runs and I'm not sure what changed.

**Comment by oliversalzburg** [comment] 2016-02-11 18:26
Sounds similar to #159 Can you share the output of what appears when you type `localStorage['cbc.kitten-scientists']` into the console?

**Comment by idgfight** [comment] 2016-02-11 18:55
"{"version":1,"items":{"toggle-hut":true,"toggle-logHouse":true,"toggle-mansion":true,"toggle-workshop":true,"toggle-factory":true,"toggle-field":true,"toggle-pasture":true,"toggle-solarFarm":true,"toggle-mine":true,"toggle-lumberMill":true,"toggle-aqueduct":true,"toggle-hydroPlant":true,"toggle-oilWell":true,"toggle-quarry":true,"toggle-smelter":true,"toggle-biolab":true,"toggle-calciner":true,"toggle-reactor":true,"toggle-accelerator":true,"toggle-steamworks":true,"toggle-magneto":true,"toggle-library":true,"toggle-academy":true,"toggle-observatory":true,"toggle-amphitheatre":true,"toggle-broadcastTower":true,"toggle-tradepost":true,"toggle-chapel":true,"toggle-temple":true,"toggle-mint":true,"toggle-unicornPasture":true,"toggle-ziggurat":true,"toggle-chronosphere":false,"toggle-barn":true,"toggle-harbor":true,"toggle-warehouse":true,"toggle-wood":true,"toggle-limited-wood":false,"toggle-beam":true,"toggle-limited-beam":false,"toggle-slab":true,"toggle-limited-slab":false,"toggle-steel":true,"toggle-limited-steel":false,"toggle-plate":true,"toggle-limited-plate":false,"toggle-alloy":true,"toggle-limited-alloy":true,"toggle-concrete":true,"toggle-limited-concrete":true,"toggle-gear":false,"toggle-limited-gear":true,"toggle-scaffold":false,"toggle-limited-scaffold":true,"toggle-ship":false,"toggle-limited-ship":true,"toggle-tanker":false,"toggle-limited-tanker":true,"toggle-parchment":true,"toggle-limited-parchment":true,"toggle-manuscript":false,"toggle-limited-manuscript":true,"toggle-compendium":false,"toggle-limited-compendium":true,"toggle-blueprint":true,"toggle-limited-blueprint":true,"toggle-kerosene":true,"toggle-limited-kerosene":true,"toggle-megalith":true,"toggle-limited-megalith":true,"toggle-eludium":true,"toggle-limited-eludium":true,"toggle-dragons":false,"toggle-dragons-spring":true,"toggle-dragons-summer":true,"toggle-dragons-autumn":true,"toggle-dragons-winter":true,"toggle-zebras":false,"toggle-zebras-spring":true,"toggle-zebras-summer":true,"toggle-zebras-autumn":true,"toggle-zebras-winter":true,"toggle-lizards":false,"toggle-lizards-spring":false,"toggle-lizards-summer":true,"toggle-lizards-autumn":false,"toggle-lizards-winter":false,"toggle-sharks":false,"toggle-sharks-spring":false,"toggle-sharks-summer":false,"toggle-sharks-autumn":false,"toggle-sharks-winter":true,"toggle-griffins":false,"toggle-griffins-spring":false,"toggle-griffins-summer":false,"toggle-griffins-autumn":true,"toggle-griffins-winter":false,"toggle-nagas":true,"toggle-nagas-spring":true,"toggle-nagas-summer":false,"toggle-nagas-autumn":false,"toggle-nagas-winter":false,"toggle-spiders":true,"toggle-spiders-spring":true,"toggle-spiders-summer":true,"toggle-spiders-autumn":true,"toggle-spiders-winter":true,"toggle-leviathans":true,"toggle-leviathans-spring":true,"toggle-leviathans-summer":true,"toggle-leviathans-autumn":true,"toggle-leviathans-winter":true,"toggle-spaceElevator":false,"toggle-sattelite":false,"toggle-spaceStation":false,"toggle-moonOutpost":false,"toggle-moonBase":false,"toggle-planetCracker":false,"toggle-hydrofracturer":false,"toggle-researchVessel":false,"toggle-orbitalArray":false,"toggle-sunlifter":false,"toggle-cryostation":true,"toggle-spaceBeacon":false},"resources":{"furs":{"stock":1000},"unobtainium":{"consume":1}},"triggers":{"faith":0.99,"hunt":0.6,"build":0.75,"space":0.01,"craft":0.95,"trade":0.95}}"

**Comment by idgfight** [comment] 2016-02-11 18:57
I can see that it isn't crafting them due to the values being false but i have them checked on

**Comment by idgfight** [comment] 2016-02-11 18:59
I refreshed the game (not the first time i've done this) and selected all the values again and it started crafting all of a sudden

**Comment by oliversalzburg** [comment] 2016-02-11 19:03
Yeah, this seems to be the same issue as #159 Something seems to trigger KS to stop recognize toggle changes and they are no longer persisted to local storage :\

So far, I'm clueless what is causing this. If this happens again and you notice some pattern or see any errors in the JS console, please let me know.

**Comment by idgfight** [comment] 2016-02-11 19:12
All I did notice was when I selected each value individually instead of setting them all with "enable all" button and then disabling the antimatter crap it worked.  I normally reset every day or so, I'll keep track of what it's doing for later restarts and resets.

**Comment by oliversalzburg** [comment] 2016-02-11 20:38
It seems the **enable all** and **disable all** links don't work as expected.

**Comment by idgfight** [comment] 2016-02-11 21:02
Well I'm glad that gives you a direction to target :)

**Comment by GronbergInfo** [comment] 2016-02-13 08:36
I can confirm, that the enable all seems to bonk it all up.
I just disabled KS, and then disabled all and manually enabling all.
Seconds after i re-enabled KS, firefox lagged for a little while (~2) and all the sudden KS builds in a frenzy, space, normal buildings, its like its on speed. :D

**Comment by Wymrite** [comment] 2019-08-13 01:26
Fixed with enable-all in #248

**Closed by Wymrite** 2019-08-13 01:26 UTC
Labels: needs:work, status:confirmed, type:bug
